### ISSUE TITLE
Help with getting the Video stream working over RTSP

### ISSUE THREAD

**Issue by rushikv** [crlane/python-mebo#4]
Trying to play around with my Mebo using your repo. Is there any way I can get the Video stream working? Trying to tinker around with the code in the stream folder, but no luck.

m.media.start_streams() gives me the Exception: supply stream password
Where do I get the stream password?

Any help is appreciated. Thanks.

**Comment by rushikv** [comment]
Figured out how to get it working. Thanks. Closing issue.

**Comment by compscirunner** [comment]
So how do you get the stream password?
